Simplify configure logics for specifying which event loop to use
  --enable-xx forces that kind of loop to be used
  --disable-xx makes sure that kind of loop is not used

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -915,14 +915,14 @@ Optional Features:
   --enable-err-languages=\"lang1 lang2..\"
                           Select languages to be installed. (All will be
                           installed by default)
+  --enable-select         Enable select() support.
+  --disable-select        Disable select() support.
   --enable-poll           Enable poll() instead of select().  Normally poll
                           is preferred over select, but configure knows poll
                           is broken on some platforms.  If you think you are
                           smarter than the configure script, you may enable
                           poll with this option.
   --disable-poll          Disable the use of poll().
-  --enable-select         Enable select() support.
-  --disable-select        Disable select() support.
   --enable-epoll          Enable epoll() instead of poll() or select().
                           epoll() is best where available, but must be
                           explicitly set at the moment.
@@ -4275,23 +4275,6 @@ _ACEOF
 
 fi;
 
-# Check whether --enable-poll or --disable-poll was given.
-if test "${enable_poll+set}" = set; then
-  enableval="$enable_poll"
-
-  case "$enableval" in
-  yes)
-    echo "Forcing poll() to be enabled"
-    ac_cv_func_poll='yes'
-    ;;
-  no)
-    echo "Forcing poll() to be disabled"
-    ac_cv_func_poll='no'
-    ;;
-  esac
-
-fi;
-
 # Check whether --enable-select or --disable-select was given.
 if test "${enable_select+set}" = set; then
   enableval="$enable_select"
@@ -4299,11 +4282,30 @@ if test "${enable_select+set}" = set; then
   case "$enableval" in
   yes)
     echo "Forcing select() to be enabled"
+    SELECT_TYPE="select"
     ac_cv_func_select='yes'
     ;;
   no)
     echo "Forcing select() to be disabled"
     ac_cv_func_select='no'
+    ;;
+  esac
+
+fi;
+
+# Check whether --enable-poll or --disable-poll was given.
+if test "${enable_poll+set}" = set; then
+  enableval="$enable_poll"
+
+  case "$enableval" in
+  yes)
+    echo "Forcing poll() to be enabled"
+    SELECT_TYPE="poll"
+    ac_cv_func_poll='yes'
+    ;;
+  no)
+    echo "Forcing poll() to be disabled"
+    ac_cv_func_poll='no'
     ;;
   esac
 
@@ -4316,6 +4318,7 @@ if test "${enable_epoll+set}" = set; then
   case "$enableval" in
   yes)
     echo "Forcing epoll() to be enabled"
+    SELECT_TYPE="epoll"
     force_epoll='yes'
     ;;
   no)
@@ -14535,8 +14538,23 @@ fi
 
 
 
-if test "$ac_cv_func_epoll_ctl" = "yes" ; then
+if test -n "$SELECT_TYPE"; then
+	: # Nothing to do
+elif test "$ac_cv_func_epoll_ctl" = "yes" ; then
         SELECT_TYPE="epoll"
+elif test "$ac_cv_func_poll" = "yes" ; then
+
+        SELECT_TYPE="poll"
+elif test "$ac_cv_func_select" = "yes" ; then
+        SELECT_TYPE="select"
+else
+        echo "Eep!  Can't find poll, epoll, or select!"
+        echo "I'll try select and hope for the best."
+        SELECT_TYPE="select"
+fi
+
+case "$SELECT_TYPE" in
+epoll)
 
 cat >>confdefs.h <<\_ACEOF
 #define USE_EPOLL 1
@@ -14611,30 +14629,26 @@ if test $ac_cv_lib_epoll_epoll_create = yes; then
 fi
 
 
-elif test "$ac_cv_func_poll" = "yes" ; then
-
-        SELECT_TYPE="poll"
+	;;
+poll)
 
 cat >>confdefs.h <<\_ACEOF
 #define USE_POLL 1
 _ACEOF
 
-elif test "$ac_cv_func_select" = "yes" ; then
-        SELECT_TYPE="select"
+	;;
+select)
 
 cat >>confdefs.h <<\_ACEOF
 #define USE_SELECT 1
 _ACEOF
 
-else
-        echo "Eep!  Can't find poll, epoll, or select!"
-        echo "I'll try select and hope for the best."
-        SELECT_TYPE="select"
-        cat >>confdefs.h <<\_ACEOF
-#define USE_SELECT 1
-_ACEOF
+	;;
+*)
+	echo "ERROR: Unknown select loop type '$SELECT_TYPE'"
+	exit 1
+esac
 
-fi
 echo "Using ${SELECT_TYPE} for select loop."
 
 
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -790,6 +790,25 @@ AC_ARG_WITH(coss-membuf-size,
    fi
 ])
 
+dnl Enable select()
+AC_ARG_ENABLE(select,
+[  --enable-select         Enable select() support.
+  --disable-select        Disable select() support. ],
+
+[
+  case "$enableval" in
+  yes)
+    echo "Forcing select() to be enabled"
+    SELECT_TYPE="select"
+    ac_cv_func_select='yes'
+    ;;
+  no)
+    echo "Forcing select() to be disabled"
+    ac_cv_func_select='no'
+    ;;
+  esac
+])
+
 dnl Enable poll()
 AC_ARG_ENABLE(poll,
 [  --enable-poll           Enable poll() instead of select().  Normally poll
@@ -802,29 +821,12 @@ AC_ARG_ENABLE(poll,
   case "$enableval" in
   yes)
     echo "Forcing poll() to be enabled"
+    SELECT_TYPE="poll"
     ac_cv_func_poll='yes'
     ;;
   no)
     echo "Forcing poll() to be disabled"
     ac_cv_func_poll='no'
-    ;;
-  esac
-])
-
-dnl Enable select()
-AC_ARG_ENABLE(select,
-[  --enable-select         Enable select() support.
-  --disable-select        Disable select() support. ],
-
-[
-  case "$enableval" in
-  yes)
-    echo "Forcing select() to be enabled"
-    ac_cv_func_select='yes'
-    ;;
-  no)
-    echo "Forcing select() to be disabled"
-    ac_cv_func_select='no'
     ;;
   esac
 ])
@@ -839,6 +841,7 @@ AC_ARG_ENABLE(epoll,
   case "$enableval" in
   yes)
     echo "Forcing epoll() to be enabled"
+    SELECT_TYPE="epoll"
     force_epoll='yes'
     ;;
   no)
@@ -2268,24 +2271,38 @@ dnl are actually going to (ab)use
 dnl Actually do the define magic now
 dnl mostly ripped from squid-commloops, thanks to adrian and benno
 
-if test "$ac_cv_func_epoll_ctl" = "yes" ; then
+if test -n "$SELECT_TYPE"; then
+	: # Nothing to do
+elif test "$ac_cv_func_epoll_ctl" = "yes" ; then
         SELECT_TYPE="epoll"
-        AC_DEFINE(USE_EPOLL,1,[Use epoll() for the IO loop])
-        AC_CHECK_LIB(epoll, epoll_create, [EPOLL_LIBS="-lepoll"])
-        AC_SUBST(EPOLL_LIBS)
 elif test "$ac_cv_func_poll" = "yes" ; then
 
         SELECT_TYPE="poll"
-        AC_DEFINE(USE_POLL,1,[Use poll() for the IO loop])
 elif test "$ac_cv_func_select" = "yes" ; then
         SELECT_TYPE="select"
-        AC_DEFINE(USE_SELECT,1,[Use select() for the IO loop])
 else
         echo "Eep!  Can't find poll, epoll, or select!"
         echo "I'll try select and hope for the best."
         SELECT_TYPE="select"
-        AC_DEFINE(USE_SELECT,1)
 fi
+
+case "$SELECT_TYPE" in
+epoll)
+        AC_DEFINE(USE_EPOLL,1,[Use epoll() for the IO loop])
+        AC_CHECK_LIB(epoll, epoll_create, [EPOLL_LIBS="-lepoll"])
+        AC_SUBST(EPOLL_LIBS)
+	;;
+poll)
+        AC_DEFINE(USE_POLL,1,[Use poll() for the IO loop])
+	;;
+select)
+        AC_DEFINE(USE_SELECT,1,[Use select() for the IO loop])
+	;;
+*)
+	echo "ERROR: Unknown select loop type '$SELECT_TYPE'"
+	exit 1
+esac
+
 echo "Using ${SELECT_TYPE} for select loop."
 AM_CONDITIONAL([USE_POLL], [test $SELECT_TYPE = poll])
 AM_CONDITIONAL([USE_EPOLL], [test $SELECT_TYPE = epoll])
