MFC: Abort the configure script if we can't find a perl executable.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -758,9 +758,15 @@ AC_PATH_PROG(RM, rm, $FALSE)
 AC_PATH_PROG(MV, mv, $FALSE)
 AC_PATH_PROG(MKDIR, mkdir, $FALSE)
 AC_PATH_PROG(LN, ln, cp)
-AC_PATH_PROG(PERL, perl, /usr/local/bin/perl)
+AC_PATH_PROG(PERL, perl, none)
 AC_PATH_PROG(MAKEDEPEND, makedepend, $TRUE)
 AC_PATH_PROG(AR, ar, $FALSE)
+
+if test "$ac_cv_path_PERL" = "none"; then
+	echo "Perl is required to compile Squid"
+	echo "Please install Perl and then re-run configure"
+	exit 1
+fi
 
 case "$host" in
     *-hp-hpux*)
