Cleanup of winbind header dependencies to correct building with current Samba releases and make migration easier in future (and also backward to older Samba versions if needed)
1. Centralize the headers to include/samba/nsswitch

2. Upgraded the headers to Samba-2.2.7a, without any changes

3. Added a --with-samba-source=... configure option to manually specify
   other headers to use (top level Samba source directory)

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -1031,6 +1031,24 @@ if test -n "$EXTERNAL_ACL_HELPERS"; then
 fi
 AC_SUBST(EXTERNAL_ACL_HELPERS)
 
+
+SAMBASOURCES='$(top_srcdir)/include/samba'
+AC_ARG_WITH(samba-sources,
+[  --with-samba-sources=/path/to/samba-source-tree
+                          Path where the correct Samba source files can be
+			  found while building winbind helpers. (defaults to
+			  use internal copies of the headers from Samba-2.2.7)
+			  ],
+[ if test -f $withval/source/nsswitch/winbind_nss_config.h; then
+	echo "Using Samba sources from $withval"
+	SAMBASOURCES="$withval/source"
+    else
+	echo "ERROR: Cannot find Samba sources at $withval"
+	exit 1
+    fi
+])
+AC_SUBST(SAMBASOURCES)
+
 dnl Disable "unlinkd" code
 AC_ARG_ENABLE(unlinkd,
 [  --disable-unlinkd       Do not use unlinkd],
